### ISSUE TITLE
Upload HighCharts Package

### ISSUE THREAD

**Issue by bmelanson2** [balapa/julian-ctas#10]
Julian purchased a pro version of HighCharts to use for graphs within wpdatatables. The zip files were too big to attach here

This is the link that was sent upon purchase for download - https://www.highcharts.com/blog/download/

There should be 4 zip files - HighCharts, Stocks, Maps, Gannt

If both of those don't work, I've also forwarded you the email confirmation.

**Comment by bmelanson2** [comment]
@balapa can you put this at the top of priority, he wants to start using the pro version of HighCharts as soon as possible

**Comment by balapa** [comment]
Are we not supposed to login first to download the pro version?

**Comment by bmelanson2** [comment]
Getting the login now

**Comment by bmelanson2** [comment]
username: juliantreves@collegetuitionadvisoryservices.com 
password: Nh3dbtbt$

**Comment by bmelanson2** [comment]
Do we have access to pro version charts?
