### ISSUE TITLE
Directory Listings

### ISSUE THREAD

**Issue by bmelanson2** [balapa/julian-ctas#11]
Pages: Students & Families, Free Materials, College Professionals, Blog index
Page Types: State Reports, College Reports

Description from the client:
"Need to build a directory allowing users to access reports & posts beyond the few recent ones highlighted in the cards. Applies to: Students & Families, Free Materials and College Pros pages. Also applies to State Reports, College Reports, and Blog"

For each of these, add a list of items that fall under the category below the main blocks of the page. If I'm a user on the College Professionals Page - I'll see the 'featured' or 'recent' 5-6 cards, then a list of other items. If I'm a user on the state reports index page and I click Alabama - I'll see a list of reports that are tagged as Alabama

**Comment by balapa** [comment]
I'm thinking to use a display feature instead. There are 2 types. Grid and List. By default, the display is grid which is what we have now. And we can change the display into list. It looks something like the image below. Let me know what you think?
![Screen Shot 2020-09-23 at 12 44 22](https://user-images.githubusercontent.com/3829210/93971509-8ec09c80-fd9a-11ea-856c-bad7c52238c1.png)

**Comment by bmelanson2** [comment]
I'll run it by the client, I would just need to see what the list view looks like

**Comment by balapa** [comment]
ok

**Comment by bmelanson2** [comment]
Any update on this? The client is looking for a timeline

**Comment by balapa** [comment]
I'll get this done tomorrow

**Comment by bmelanson2** [comment]
was this deployed?

**Comment by balapa** [comment]
Yes. If you don't see it, remove your cache first.
