### ISSUE TITLE
Free Membership - ask for email

### ISSUE THREAD

**Issue by bmelanson2** [balapa/julian-ctas#13]
Description from client: "For the Free membership, users joining need to be asked for their e-mails"

**Comment by balapa** [comment]
Currently, the restrict content pro require most of these fields to be filled on free membership. And yes, the email is included here. 
![Screen Shot 2020-09-22 at 16 49 16](https://user-images.githubusercontent.com/3829210/93867768-b7418b80-fcf3-11ea-8010-f811d01a72ee.png)
