### ISSUE TITLE
General Questions

### ISSUE THREAD

**Issue by bmelanson2** [balapa/julian-ctas#18]
Didn't know the best way of documenting general questions I have, so I'm writing them in an issue: 

- In the main database, all colleges have a unique id (labeled IPEDID) - is it possible to create a template that dynamically displays information/data based on that id? Let's say a user is on the college reports section and selects Harvard University - instead of having to create an individual report for Harvard University (there are over 2k+ colleges so it's a lot of manual reports) the template would take Harvard's unique ID, and pull the relevant information from the database to display on the report. This is NOT for v1 of the site, I'm just curious if this is possible

- wpdatatables - is it possible to change the naming of shortcodes from numbers [wpdatatable id=20] to names of the reports [wpdatatables id=alabama]

- Reading Time WP Plugin - are we using this?

**Comment by balapa** [comment]
Answer to question #1 
That would be a better solution. I'll look it up

Answer to question #2
I think it's not possible. Why do you ask?

Answer to question #3
In the homepage design, there's an information about a reading time in the post item. We need this plugin to determine the reading time. However, Julian hasn't mentioned anything about it. Please ask him if he wants to use it or not.
