### ISSUE TITLE
QR Code on Contact Page

### ISSUE THREAD

**Issue by bmelanson2** [balapa/julian-ctas#19]
I know we had discussed that we weren't going to use this, but the client is pretty adamant about seeing if this will be useful. 

For now, let's just put the QR code on the contact page - you can use something like either of these: 
https://www.qr-code-generator.com/solutions/epc-qr-code/
https://www.qr-code-generator.com/

It doesn't have to work properly at the moment, it's more about just being on the page. 

Here's the design for it: https://xd.adobe.com/view/2a38f8b3-1b76-4c04-8871-82361acd4ccb-7f6b/screen/b00b6316-6cb7-45dd-9466-b9c9b8123ea9

**Comment by balapa** [comment]
I wonder if Julian likes the idea of putting the QR code as banner on top of the page. Can you ask him?
![Screen Shot 2020-09-22 at 19 37 24](https://user-images.githubusercontent.com/3829210/93882986-1f4f9c00-fd0b-11ea-990f-b9acbeda3488.png)

**Comment by bmelanson2** [comment]
I'll send it to him now

**Comment by bmelanson2** [comment]
Response from client: "The QR positioning is fine.  First thing they see so it's obvious - good choice."

**Comment by bmelanson2** [comment]
Stack it differently on mobile views, otherwise this is good

![Screen Shot 2020-09-23 at 8 30 37 AM](https://user-images.githubusercontent.com/66379580/94012688-20b6ae00-fd77-11ea-999b-8b9dc07d3432.png)

**Comment by balapa** [comment]
sure
