### ISSUE TITLE
CSS for headers, lists, etc

### ISSUE THREAD

**Issue by bmelanson2** [balapa/julian-ctas#20]
http://159.89.48.136/blog/styles/

Is there any CSS for headers, lists, text on any of the pages? Is this something that the designer was supposed to provide?

Not having a way to distinguish different blocks/sections on the frontend is an issue - let me know our options 

![Screen Shot 2020-09-28 at 9 29 11 PM](https://user-images.githubusercontent.com/66379580/94502240-bae08100-01d1-11eb-812d-96c691bb9c1c.png)
![Screen Shot 2020-09-28 at 9 29 26 PM](https://user-images.githubusercontent.com/66379580/94502241-bae08100-01d1-11eb-921a-6ce33adc67e2.png)

**Comment by balapa** [comment]
Yes. I will work on this

**Comment by bmelanson2** [comment]
Any update on this? The client is looking for a timeline

**Comment by balapa** [comment]
I'll get this done tomorrow

**Comment by Shubhainder** [comment]
Hey, I can work on this, can finish it really fast. You need this page as shown in the picture? or anything in particular
