### ISSUE TITLE
Update College Pros Template to be Editable

### ISSUE THREAD

**Issue by bmelanson2** [balapa/julian-ctas#21]
For the College Pros pages - use the same template you use for state reports, college reports, etc. The client likes the ability to edit/add blocks of text/images on each College Pro page, the same way it's already being done for state and college reports

![Screen Shot 2020-09-28 at 9 30 49 PM](https://user-images.githubusercontent.com/66379580/94502413-13b01980-01d2-11eb-9665-9ad1235462b8.png)
![Screen Shot 2020-09-28 at 9 30 36 PM](https://user-images.githubusercontent.com/66379580/94502414-13b01980-01d2-11eb-8388-f54b6480bbc5.png)

**Comment by balapa** [comment]
fixed
